//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowInstanceDetails
    {
        public int Id { get; set; }
        public int ShowInstanceId { get; set; }
        public string LanguageCode { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string LongDescription { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual ShowInstance ShowInstance { get; set; }
    }
}
