//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WrestlingEntities : DbContext
    {
        public WrestlingEntities()
            : base("name=WrestlingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Show> Show { get; set; }
        public virtual DbSet<ShowInstance> ShowInstance { get; set; }
        public virtual DbSet<Wrestler> Wrestler { get; set; }
        public virtual DbSet<CompanyDetails> CompanyDetails { get; set; }
        public virtual DbSet<ShowDetails> ShowDetails { get; set; }
        public virtual DbSet<ShowInstanceDetails> ShowInstanceDetails { get; set; }
        public virtual DbSet<WrestlerDetails> WrestlerDetails { get; set; }
    }
}
